import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync,readFileSync,existsSync,writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../src/server/app.js';
import { createProviders } from '../src/providers/index.js';
import type { CallProvider } from '../src/shared/contracts.js';
import { installIntegration,uninstallIntegration } from '../src/bridge/integration.js';
import { mapCodexEvent,ManagedCodex } from '../src/bridge/codex.js';
import { ConfigStore } from '../src/core/config.js';
import { canonicalDestination } from '../src/core/destination.js';

async function setup(){const dir=mkdtempSync(join(tmpdir(),'acb-test-'));const app=await createApp({dataDir:dir,projectRoot:dir,testMode:true});await app.ready();return {dir,app,headers:{authorization:`Bearer ${app.localToken}`},async close(){await app.close();rmSync(dir,{recursive:true,force:true});}};}
const event=(overrides:any={})=>({eventId:'event-1',taskId:'task-1',source:'test-agent',type:'task_completed',summary:'测试任务完成',...overrides});
async function idle(app:any){for(let i=0;i<30;i++){await app.acb.drain();if(app.acb.notifications().every((r:any)=>r.status!=='dialing'))break;await new Promise(r=>setTimeout(r,10));}}

test('API rejects missing auth, foreign host and origin',async()=>{const s=await setup();try{assert.equal((await s.app.inject('/api/status')).statusCode,401);assert.equal((await s.app.inject({url:'/api/status',headers:{...s.headers,host:'evil.example'}})).statusCode,403);assert.equal((await s.app.inject({url:'/api/status',headers:{...s.headers,origin:'https://evil.example'}})).statusCode,403);assert.equal((await s.app.inject({url:'/api/status',headers:s.headers})).statusCode,200);}finally{await s.close();}});
test('encoded route cannot bypass management authorization',async()=>{const s=await setup();try{for(const url of ['/%61pi/config','/api/%63onfig','/%2561pi/config'])assert.notEqual((await s.app.inject({url})).statusCode,200);assert.notEqual((await s.app.inject({method:'POST',url:'/%61pi/real-calls/enable',payload:{confirmation:'我确认线路可用并同意受限自动外呼及可能费用'}})).statusCode,200);}finally{await s.close();}});
test('one data directory cannot start concurrent queue workers',async()=>{const s=await setup();try{await assert.rejects(createApp({dataDir:s.dir,projectRoot:s.dir,testMode:true}),/已有 Bridge 实例/);}finally{await s.close();}});
test('restart revokes unconsumed real call authorization',async()=>{const s=await setup();try{s.app.acb.updateConfig({mode:'twilio',recipient:{countryCode:'+1',number:'2025550101',consent:true}});s.app.acb.accept(event());s.app.acb.store.run("UPDATE notifications SET status='queued',authorized=1,next_at=?",Date.now()+60000);await s.app.close();const restarted=await createApp({dataDir:s.dir,projectRoot:s.dir,testMode:true});assert.equal(restarted.acb.notifications()[0].status,'awaiting_authorization');assert.equal(restarted.acb.realCallsEnabled,false);await restarted.close();}finally{rmSync(s.dir,{recursive:true,force:true});}});
test('config encrypted, secrets and numbers masked; blank preserves and null clears',async()=>{const s=await setup();try{s.app.acb.updateConfig({recipient:{number:'2025550101'},providers:{twilio:{authToken:'unit-test-secret'}}});const masked=s.app.acb.config.masked();assert.equal(masked.providers.twilio.authToken,'');assert.equal(masked.recipient.number,'');assert.equal(masked.recipient.hasNumber,true);assert.ok(!readFileSync(join(s.dir,'config.enc'),'utf8').includes('unit-test-secret'));s.app.acb.updateConfig({recipient:{number:''},providers:{twilio:{authToken:''}}});assert.equal(s.app.acb.config.read().recipient.number,'2025550101');assert.equal(s.app.acb.config.read().providers.twilio.authToken,'unit-test-secret');s.app.acb.updateConfig({providers:{twilio:{authToken:null}}});assert.equal(s.app.acb.config.read().providers.twilio.authToken,'');}finally{await s.close();}});
test('Mock chain persists, duplicate event never redials and turn finished is suppressed',async()=>{const s=await setup();try{const first=s.app.acb.accept(event());const second=s.app.acb.accept(event());assert.equal(second.duplicate,true);assert.equal(first.notification.id,second.notification.id);await idle(s.app);assert.equal(s.app.acb.notifications()[0].status,'completed');assert.equal(s.app.acb.notifications()[0].attempts,1);assert.equal(s.app.acb.accept(event({eventId:'turn',type:'turn_finished'})).notification.status,'suppressed');assert.throws(()=>s.app.acb.accept(event({taskId:'wrong'})),/绑定/);}finally{await s.close();}});
test('idempotency rejects changed thread identity or choices',async()=>{const s=await setup();try{const original=event({threadId:'original',type:'decision_required',decision:{question:'继续？',options:[{id:'yes',label:'继续'},{id:'no',label:'停止'}]}});s.app.acb.accept(original);assert.throws(()=>s.app.acb.accept({...original,threadId:'different'}));assert.throws(()=>s.app.acb.accept({...original,decision:{...original.decision,options:[{id:'run',label:'执行命令'},{id:'no',label:'停止'}]}}));}finally{await s.close();}});
test('decisions bind task, accept whitelist once, reject stale and unknown options',async()=>{const s=await setup();try{const d=s.app.acb.accept(event({type:'decision_required',threadId:'thread-1',decision:{question:'继续？',options:[{id:'continue',label:'继续'},{id:'stop',label:'停止'}]}})).decision;assert.equal(d.threadId,'thread-1');await assert.rejects(s.app.acb.respondDecision({decisionId:d.id,optionId:'run-shell'}));await s.app.acb.respondDecision({decisionId:d.id,optionId:'continue'});await assert.rejects(s.app.acb.respondDecision({decisionId:d.id,optionId:'stop'}));assert.equal(s.app.acb.decision(d.id).answer.label,'继续');const d2=s.app.acb.accept(event({eventId:'expired',type:'decision_required',decision:{question:'继续？',options:[{id:'continue',label:'继续'},{id:'stop',label:'停止'}]}})).decision;s.app.acb.store.run('UPDATE decisions SET expires_at=? WHERE id=?',Date.now()-1,d2.id);await assert.rejects(s.app.acb.respondDecision({decisionId:d2.id,optionId:'continue'}));}finally{await s.close();}});
test('real calls require separate explicit authorization and honor limits/pause/config revocation',async()=>{const s=await setup();let dialed=0;const fake:CallProvider={id:'twilio',check:async()=>({ok:true,message:'fake'}),dial:async()=>{dialed++;return {status:'completed'};},cancel:async()=>({ok:true,message:'fake'})};s.app.acb.providers.twilio=fake;try{s.app.acb.updateConfig({mode:'twilio',recipient:{countryCode:'+1',number:'2025550101',consent:true}});const n=s.app.acb.accept(event()).notification;await idle(s.app);assert.equal(dialed,0);assert.equal(n.status,'awaiting_authorization');assert.throws(()=>s.app.acb.authorize(n.id,'yes'));s.app.acb.authorize(n.id,'拨打本次真实电话');await idle(s.app);assert.equal(dialed,1);s.app.acb.enableReal('我确认线路可用并同意受限自动外呼及可能费用');s.app.acb.accept(event({eventId:'limited'}));await idle(s.app);assert.equal(dialed,1);assert.ok(s.app.acb.notifications().some(n=>n.status==='suppressed'));await s.app.acb.pause(true);s.app.acb.accept(event({eventId:'paused'}));assert.equal(s.app.acb.realCallsEnabled,false);assert.equal(dialed,1);s.app.acb.updateConfig({voice:{rate:1}});assert.equal(s.app.acb.realCallsEnabled,false);}finally{await s.close();}});
test('unknown provider outcome never retries and in-flight restart becomes unknown',async()=>{const s=await setup();try{s.app.acb.providers.mock={id:'mock',check:async()=>({ok:true,message:'fake'}),dial:async()=>({status:'unknown',retryable:true}),cancel:async()=>({ok:true,message:'fake'})};s.app.acb.accept(event());await idle(s.app);await s.app.acb.drain();assert.equal(s.app.acb.notifications()[0].attempts,1);assert.equal(s.app.acb.notifications()[0].status,'unknown');s.app.acb.store.run("UPDATE notifications SET status='dialing'");await s.app.close();const second=await createApp({dataDir:s.dir,projectRoot:s.dir,testMode:true});assert.equal(second.acb.notifications()[0].status,'unknown');await second.close();}finally{rmSync(s.dir,{recursive:true,force:true});}});
test('retry budget bounded and pause preserves queued Mock',async()=>{const s=await setup();let calls=0;try{s.app.acb.updateConfig({notification:{maxRetries:1}});s.app.acb.providers.mock={id:'mock',check:async()=>({ok:true,message:'fake'}),dial:async()=>{calls++;return {status:'failed',retryable:true};},cancel:async()=>({ok:true,message:'fake'})};await s.app.acb.pause(true);s.app.acb.accept(event());assert.equal(calls,0);await s.app.acb.pause(false);await idle(s.app);s.app.acb.store.run('UPDATE notifications SET next_at=0');await idle(s.app);assert.equal(calls,2);assert.equal(s.app.acb.notifications()[0].status,'failed');}finally{await s.close();}});
test('integration install preserves unrelated instructions and uninstall removes only its block',()=>{const dir=mkdtempSync(join(tmpdir(),'acb-integration-'));try{writeFileSync(join(dir,'AGENTS.md'),'Original rules\n');installIntegration(dir,dir);installIntegration(dir,dir);const text=readFileSync(join(dir,'AGENTS.md'),'utf8');assert.equal(text.split('<!-- agent-call-bridge:start -->').length,2);assert.ok(text.startsWith('Original rules'));uninstallIntegration(dir);assert.ok(readFileSync(join(dir,'AGENTS.md'),'utf8').includes('Original rules'));assert.ok(!readFileSync(join(dir,'AGENTS.md'),'utf8').includes('agent-call-bridge:start'));assert.ok(existsSync(join(dir,'integration-backup.json')));}finally{rmSync(dir,{recursive:true,force:true});}});
test('Codex mapping ignores foreign threads and retries; completed turn is not task accepted',()=>{const own=new Map([['thread-1','task-1']]);assert.equal(mapCodexEvent({method:'turn/completed',params:{threadId:'other',turn:{status:'completed'}}},own),null);assert.equal(mapCodexEvent({method:'error',params:{threadId:'thread-1',willRetry:true}},own),null);assert.equal(mapCodexEvent({method:'turn/completed',params:{threadId:'thread-1',turn:{status:'completed'}}},own)?.type,'turn_finished');assert.equal(mapCodexEvent({method:'turn/completed',params:{threadId:'thread-1',turn:{status:'failed'}}},own)?.type,'task_failed');});
test('accepted call occupies the single slot; repeated poll reaches terminal and pause requests cancellation',async()=>{const s=await setup();let calls=0,polls=0,cancels=0;try{s.app.acb.providers.mock={id:'mock',check:async()=>({ok:true,message:'fake'}),dial:async()=>({status:'accepted',callId:`fake-${++calls}`}),poll:async()=>({status:++polls<2?'accepted':'completed'}),cancel:async()=>{cancels++;return {ok:true,message:'请求停止'};}};s.app.acb.accept(event());await idle(s.app);s.app.acb.accept(event({eventId:'second'}));await idle(s.app);assert.equal(calls,1);await s.app.acb.pause(true);assert.equal(cancels,1);s.app.acb.store.run("UPDATE notifications SET next_at=0 WHERE status='accepted'");await s.app.acb.drain();assert.equal(polls,1);s.app.acb.store.run("UPDATE notifications SET next_at=0 WHERE status='accepted'");await s.app.acb.drain();assert.equal(polls,2);await s.app.acb.pause(false);await s.app.acb.drain();assert.equal(calls,2);}finally{await s.close();}});
test('provider timeout is unknown and not requeued',async()=>{const s=await setup();try{s.app.acb.providers.mock={id:'mock',check:async()=>({ok:true,message:'fake'}),dial:()=>new Promise(()=>{}),cancel:async()=>({ok:true,message:'fake'})};s.app.acb.accept(event());await new Promise(r=>setTimeout(r,350));assert.equal(s.app.acb.notifications()[0].status,'unknown');assert.equal(s.app.acb.notifications()[0].attempts,1);}finally{await s.close();}});
test('Windows DPAPI roundtrip preserves Chinese without plaintext secret file',()=>{if(process.platform!=='win32')return;const dir=mkdtempSync(join(tmpdir(),'acb-dpapi-'));try{const c=new ConfigStore(dir);c.update({voice:{name:'中文测试'},providers:{twilio:{authToken:'dpapi-fixture-secret'}}});const d=new ConfigStore(dir);assert.equal(d.read().voice.name,'中文测试');assert.equal(d.read().providers.twilio.authToken,'dpapi-fixture-secret');assert.ok(!readFileSync(join(dir,'config.enc'),'utf8').includes('dpapi-fixture-secret'));assert.equal(existsSync(join(dir,'local.key')),false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('stall watchdog only monitors explicitly registered active tasks and suppresses repeats',async()=>{const s=await setup();try{s.app.acb.updateConfig({notification:{stallMinutes:1}});s.app.acb.heartbeat({taskId:'active',source:'test-agent',threadId:'t'});s.app.acb.heartbeat({taskId:'finished',source:'test-agent',threadId:'f'});s.app.acb.accept(event({eventId:'finished',taskId:'finished',threadId:'f'}));await idle(s.app);s.app.acb.store.run('UPDATE task_monitors SET last_seen=?',Date.now()-120000);await s.app.acb.drain();await s.app.acb.drain();const stalled=s.app.acb.events().filter(e=>e.type==='task_stalled');assert.equal(stalled.length,1);assert.equal(stalled[0].taskId,'active');assert.throws(()=>s.app.acb.heartbeat({taskId:'active',source:'test-agent',threadId:'foreign'}));}finally{await s.close();}});
test('managed Codex rejects foreign approvals, stale/partial answers and duplicate consumption',()=>{const c:any=new ManagedCodex('unused',()=>{},()=>{throw new Error('foreign approval leaked');});c.receive(JSON.stringify({method:'item/commandExecution/requestApproval',id:1,params:{threadId:'foreign'}})+'\n');c.owned.set('owned','task');const writes:string[]=[];c.child={stdin:{write:(text:string)=>writes.push(text)}};c.questions.set(2,{threadId:'owned',expiresAt:Date.now()+10000,questions:[{id:'q',options:[{label:'继续'},{label:'停止'}]}]});assert.throws(()=>c.answer(2,{}));assert.throws(()=>c.answer(2,{q:{answers:[]}}));assert.throws(()=>c.answer(2,{q:{answers:['任意命令']}}));c.answer(2,{q:{answers:['继续']}});assert.equal(writes.length,1);assert.throws(()=>c.answer(2,{q:{answers:['继续']}}));c.child=undefined;});
test('SIP authorization uses canonical SIP target without a phone number and honors consent/limits',async()=>{const s=await setup();const targets:string[]=[];try{s.app.acb.providers.sip={id:'sip',check:async()=>({ok:true,message:'fake'}),dial:async request=>{targets.push(request.to);return {status:'completed'};},cancel:async()=>({ok:true,message:'fake'})};s.app.acb.updateConfig({mode:'sip',recipient:{number:null,consent:false},providers:{sip:{server:'PBX.Example',extension:'desk-201',port:5070,transport:'TCP'}}});assert.equal(s.app.acb.config.read().recipient.number,'');assert.equal(canonicalDestination(s.app.acb.config.read()),'sip:desk-201@pbx.example:5070;transport=tcp');const n=s.app.acb.accept(event()).notification;assert.throws(()=>s.app.acb.authorize(n.id,'拨打本次真实电话'));assert.throws(()=>s.app.acb.enableReal('我确认线路可用并同意受限自动外呼及可能费用'));s.app.acb.updateConfig({recipient:{consent:true}});s.app.acb.authorize(n.id,'拨打本次真实电话');await idle(s.app);assert.deepEqual(targets,['sip:desk-201@pbx.example:5070;transport=tcp']);s.app.acb.enableReal('我确认线路可用并同意受限自动外呼及可能费用');s.app.acb.accept(event({eventId:'sip-rate-limit'}));await idle(s.app);assert.equal(targets.length,1);assert.ok(s.app.acb.notifications().some(n=>n.status==='suppressed'));}finally{await s.close();}});
test('SIP destination changes revoke queued authorization and cannot redirect an old notification',async()=>{const s=await setup();let calls=0;try{s.app.acb.providers.sip={id:'sip',check:async()=>({ok:true,message:'fake'}),dial:async()=>{calls++;return {status:'completed'};},cancel:async()=>({ok:true,message:'fake'})};await s.app.acb.pause(true);s.app.acb.updateConfig({mode:'sip',recipient:{number:null,consent:true},providers:{sip:{server:'pbx.example',extension:'201'}}});s.app.acb.enableReal('我确认线路可用并同意受限自动外呼及可能费用');const n=s.app.acb.accept(event()).notification;assert.equal(n.status,'queued');s.app.acb.updateConfig({providers:{sip:{extension:'202'}}});assert.equal(s.app.acb.realCallsEnabled,false);assert.equal(s.app.acb.notifications()[0].status,'awaiting_authorization');assert.throws(()=>s.app.acb.authorize(n.id,'拨打本次真实电话'),/目标/);await s.app.acb.pause(false);await idle(s.app);assert.equal(calls,0);}finally{await s.close();}});

