import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

test.beforeEach(async ({ page }) => {
  const connection = JSON.parse(readFileSync(join(process.env.ACB_UI_TEST_DIR!, 'connection.json'), 'utf8'));
  await page.goto(`/#token=${connection.token}`);
  await expect(page.getByText('Bridge 运行中', { exact: true })).toBeVisible();
});
test('首次启动向导、Mock通知、配置保存和重载', async ({ page }) => {
  await expect(page.getByRole('heading', { name: '先建立一条安心的连接' })).toBeVisible();
  await page.getByRole('button', { name: '稍后配置，进入工作台' }).click();
  await page.getByRole('button', { name: '运行模拟通话' }).click();
  await expect(page.getByRole('status')).toContainText('不会拨打真实号码');
  await expect(page.getByText('模拟完成', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: '通话设置', exact: true }).click();
  await page.getByLabel('无进展提醒（分钟）').fill('20');
  await page.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('设置已保存');
  await page.reload();
  await page.getByRole('button', { name: '通话设置', exact: true }).click();
  await expect(page.getByLabel('无进展提醒（分钟）')).toHaveValue('20');
  await page.getByRole('button', { name: '工作台', exact: true }).click();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: '.local/ui-workbench.png', fullPage: true });
});
test('暂停/恢复、中文语音和受限线路提示', async ({ page }) => {
  const skip=page.getByRole('button', { name: '稍后配置，进入工作台' }); if(await skip.isVisible())await skip.click();
  await page.getByRole('button', { name: '紧急停止', exact: true }).click();
  await expect(page.getByText('通知已暂停', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '恢复通知', exact: true }).click();
  await expect(page.getByText('Bridge 运行中', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '通话设置', exact: true }).click();
  await page.getByRole('combobox', { name: '电话服务', exact: true }).selectOption('twilio');
  await expect(page.getByText(/Twilio 不支持中国大陆/)).toBeVisible();
  const help=page.getByRole('region',{name:'服务申请入口'});
  await expect(help.getByRole('link',{name:'注册 / 登录 Twilio',exact:true})).toHaveAttribute('href','https://www.twilio.com/try-twilio');
  await expect(help.getByRole('link',{name:'注册 / 登录 Twilio',exact:true})).toHaveAttribute('rel','noopener noreferrer');
  await help.screenshot({path:'.local/ui-provider-links.png'});
  await page.getByRole('combobox',{name:'电话服务',exact:true}).selectOption('aliyun');
  await expect(help.getByRole('link',{name:'打开语音控制台',exact:true})).toHaveAttribute('href','https://dyvms.console.aliyun.com/dyvms.htm');
  await expect(help.getByRole('link',{name:'查看企业申请条件',exact:true})).toBeVisible();
  await expect(help.getByRole('link',{name:'注册 / 登录 Twilio',exact:true})).toHaveCount(0);
  await page.getByRole('combobox',{name:'电话服务',exact:true}).selectOption('sip');
  await expect(help.getByText(/SIP 没有统一的申请网站/)).toBeVisible();
  await expect(help.getByRole('link',{name:'查看 SIP / 座机接入指南',exact:true})).toBeVisible();
  await page.getByRole('combobox', { name: '电话服务', exact: true }).selectOption('mock');
  await expect(help).toHaveCount(0);
  await page.getByRole('button', { name: '生成中文试听', exact: true }).click();
  await expect(page.getByLabel('中文语音试听')).toBeVisible();
  await expect.poll(() => page.locator('audio').evaluate((a: HTMLAudioElement) => a.readyState)).toBeGreaterThanOrEqual(1);
  expect(await page.locator('audio').evaluate((a: HTMLAudioElement) => a.duration)).toBeGreaterThan(1);
});
test('真实后台待决定事件可在界面回复，重复答复拒绝', async ({ page, request }) => {
  const skip=page.getByRole('button', { name: '稍后配置，进入工作台' }); if(await skip.isVisible())await skip.click();
  const connection=JSON.parse(readFileSync(join(process.env.ACB_UI_TEST_DIR!, 'connection.json'), 'utf8'));
  const headers={Authorization:`Bearer ${connection.token}`};
  const response=await request.post('/api/events',{headers,data:{eventId:crypto.randomUUID(),taskId:'ui-decision-fixture',source:'ui-test-fixture',type:'decision_required',summary:'这是UI自动化夹具，不是真实Agent任务',decision:{question:'选择下一步验证方式',options:[{id:'continue',label:'继续本地验证'},{id:'stop',label:'停止本地验证'}]}}});
  expect(response.ok()).toBeTruthy(); const data=await response.json();
  await page.getByRole('button',{name:'继续本地验证',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('答复已保存');
  const decision=await request.get(`/api/decisions/${data.decision.id}`,{headers});
  expect((await decision.json()).optionId).toBe('continue');
  const duplicate=await request.post(`/api/decisions/${data.decision.id}/respond`,{headers,data:{optionId:'stop'}}); expect(duplicate.ok()).toBeFalsy();
});
test('未认证请求被拒绝，敏感配置不进入页面', async ({ page, request }) => {
  const unauth=await request.get('/api/config'); expect(unauth.status()).toBe(401);
  const secret=JSON.parse(readFileSync(join(process.env.ACB_UI_TEST_DIR!, 'connection.json'), 'utf8')).token;
  expect(await page.locator('body').innerText()).not.toContain(secret);
  expect(page.url()).not.toContain(secret);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
test('SIP 无手机号配置可保存，准备真实测试保持零次拨号', async ({ page, request }) => {
  const skip=page.getByRole('button', { name: '稍后配置，进入工作台' }); if(await skip.isVisible())await skip.click();
  const connection=JSON.parse(readFileSync(join(process.env.ACB_UI_TEST_DIR!, 'connection.json'), 'utf8'));
  const headers={Authorization:`Bearer ${connection.token}`};
  await page.getByRole('button',{name:'通话设置',exact:true}).click();
  await page.getByRole('combobox',{name:'电话服务',exact:true}).selectOption('sip');
  await page.getByLabel('SIP 服务器',{exact:true}).fill('127.0.0.1');
  await page.getByLabel('目标分机 / SIP 地址',{exact:true}).fill('fixture');
  await page.getByRole('button',{name:'保存设置',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('设置已保存');
  await page.getByRole('button',{name:'准备真实测试（先审核）',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('尚未拨号');
  await page.getByRole('button',{name:'审核这次通话',exact:true}).click();
  await expect(page.getByRole('button',{name:'确认并拨打这一次',exact:true})).toBeDisabled();
  const records=await (await request.get('/api/notifications',{headers})).json();
  const prepared=records.find((n:any)=>n.taskId==='real-test');
  expect(prepared.status).toBe('awaiting_authorization'); expect(prepared.attempts).toBe(0);
  await page.setViewportSize({width:360,height:844});
  await expect(page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'通话设置',exact:true})).toHaveAttribute('aria-current','page');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);
  await page.getByLabel('输入“拨打本次真实电话”').focus();
  await expect(page.getByLabel('输入“拨打本次真实电话”')).toBeFocused();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({path:'.local/ui-settings-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'通知记录',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);
  await page.screenshot({path:'.local/ui-history-mobile.png',fullPage:true});
  const restore=await request.put('/api/config',{headers,data:{mode:'mock'}}); expect(restore.ok()).toBeTruthy();
});
