import { spawn } from 'node:child_process';
const base="[Console]::InputEncoding=[Text.UTF8Encoding]::new($false); [Console]::OutputEncoding=[Text.UTF8Encoding]::new($false); Add-Type -AssemblyName System.Speech; $inputJson=[Console]::In.ReadToEnd() | ConvertFrom-Json; $s=New-Object System.Speech.Synthesis.SpeechSynthesizer; ";
async function run(script:string,input:unknown){if(process.platform!=='win32')throw new Error('本地中文语音需要 Windows；其他系统仍可使用 Mock 文本');return new Promise<string>((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',base+script],{windowsHide:true,stdio:['pipe','pipe','pipe']});let output='';let size=0;const t=setTimeout(()=>{p.kill();reject(new Error('本地语音超时'));},20000);p.stdout.on('data',d=>{size+=d.length;if(size>16*1024*1024){p.kill();reject(new Error('语音结果过大'));}else output+=d.toString();});p.stderr.resume();p.on('error',()=>{clearTimeout(t);reject(new Error('无法启动 Windows 语音服务'));});p.on('close',code=>{clearTimeout(t);code===0?resolve(output.trim()):reject(new Error('语音生成失败；请检查 Windows 中文语音安装情况'));});p.stdin.end(JSON.stringify(input));});}
export async function listVoices(){const output=await run("$v=@($s.GetInstalledVoices() | ForEach-Object { @{id=$_.VoiceInfo.Name; name=$_.VoiceInfo.Name; language=$_.VoiceInfo.Culture.Name} }); ConvertTo-Json -InputObject $v -Compress; $s.Dispose()",{});return JSON.parse(output);}
async function render(text:string,voice:string,rate:number,telephony:boolean):Promise<Buffer>{
  if(typeof text!=='string'||!text.trim()||text.length>1000)throw new Error('语音文本须为 1–1000 字符');if(!Number.isInteger(rate)||rate < -10||rate>10)throw new Error('语速无效');
  const output=await run("$s.Rate=[int]$inputJson.rate; if($inputJson.voice){$s.SelectVoice([string]$inputJson.voice)} else {$v=$s.GetInstalledVoices() | Where-Object {$_.VoiceInfo.Culture.Name -like 'zh-*'} | Select-Object -First 1; if(-not $v){throw 'Chinese voice not installed'}; $s.SelectVoice($v.VoiceInfo.Name)}; $stream=New-Object IO.MemoryStream; if($inputJson.telephony){$format=New-Object System.Speech.AudioFormat.SpeechAudioFormatInfo(8000,[System.Speech.AudioFormat.AudioBitsPerSample]::Sixteen,[System.Speech.AudioFormat.AudioChannel]::Mono); $s.SetOutputToAudioStream($stream,$format)} else {$s.SetOutputToWaveStream($stream)}; $s.Speak([string]$inputJson.text); [Convert]::ToBase64String($stream.ToArray()); $s.Dispose(); $stream.Dispose()",{text,voice,rate,telephony});
  const pcm=Buffer.from(output,'base64');if(!telephony)return pcm;
  const header=Buffer.alloc(44);header.write('RIFF',0);header.writeUInt32LE(36+pcm.length,4);header.write('WAVEfmt ',8);header.writeUInt32LE(16,16);header.writeUInt16LE(1,20);header.writeUInt16LE(1,22);header.writeUInt32LE(8000,24);header.writeUInt32LE(16000,28);header.writeUInt16LE(2,32);header.writeUInt16LE(16,34);header.write('data',36);header.writeUInt32LE(pcm.length,40);return Buffer.concat([header,pcm]);
}
export function synthesize(text:string,voice='',rate=0){return render(text,voice,rate,false);}
export function synthesizeTelephony(text:string,voice='',rate=0){return render(text,voice,rate,true);}
