import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { AppConfig, ProviderId, EventType } from '../shared/contracts';
import './style.css';
import { RealCalls } from './RealCalls';
import { ProviderHelp } from './ProviderHelp';

const tokenFromHash = new URLSearchParams(location.hash.slice(1)).get('token');
if (tokenFromHash) { sessionStorage.setItem('acb-token', tokenFromHash); history.replaceState(null, '', location.pathname); }
const token = () => sessionStorage.getItem('acb-token') ?? '';
async function api<T = any>(path: string, body?: unknown, method?: string): Promise<T> {
  const response = await fetch(`/api${path}`, { method: method ?? (body === undefined ? 'GET' : 'POST'), headers: { Authorization: `Bearer ${token()}`, ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}) }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message ?? data.error ?? `请求失败（${response.status}）`);
  return data as T;
}
const names: Record<ProviderId, string> = { mock: 'Mock 演示', twilio: 'Twilio', aliyun: '阿里云语音', sip: 'SIP 网络电话' };
const eventNames: Record<EventType, string> = { task_completed: '任务报告完成', task_failed: '任务失败', task_stalled: '疑似无进展', retry_exhausted: '重试耗尽', decision_required: '需要决定', turn_finished: '轮次结束' };
const statusNames: Record<string, string> = { completed: '模拟完成', accepted: '服务商已受理', failed: '失败', unknown: '受理结果未知', pending: '等待回复', queued: '排队中', sending: '处理中', awaiting_authorization: '等待真实拨号授权', suppressed: '已抑制', rate_limited: '已限频', cancelled: '已停止', answered: '已回复', resolved: '已回复', consumed: '已送回 Agent', expired: '已过期', paused: '已暂停', retrying: '等待重试', delivered: '已完成' };
function dt(value?: string | number) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false, month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '暂无记录'; }
function Icon({ name = 'phone', size = 20 }: { name?: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    phone: <path d="M6 3h3l2 5-2 2a16 16 0 0 0 5 5l2-2 5 2v3a3 3 0 0 1-3 3C9 21 3 15 3 6a3 3 0 0 1 3-3Z" />,
    grid: <><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,
    settings: <><path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/></>,
    link: <><path d="m10 13 4-4m-5 7-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 0 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/></>,
    list: <><path d="M8 5h13M8 12h13M8 19h13M3 5h.01M3 12h.01M3 19h.01"/></>,
    arrow: <path d="M5 12h14m-5-5 5 5-5 5"/>,
    play: <path d="m8 4 12 8-12 8Z"/>,
    shield: <><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    stop: <rect x="5" y="5" width="14" height="14" rx="2"/>,
    wave: <path d="M3 10v4m4-8v12m5-15v18m5-15v12m4-8v4"/>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] ?? paths.phone}</svg>;
}
function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}{help && <small>{help}</small>}</label>; }
function App() {
  const [page, setPage] = useState('overview');
  const [config, setConfig] = useState<AppConfig | null>(null);
  const [status, setStatus] = useState<any>(null);
  const [events, setEvents] = useState<any[]>([]);
  const [notifications, setNotifications] = useState<any[]>([]);
  const [decisions, setDecisions] = useState<any[]>([]);
  const [integration, setIntegration] = useState<any>(null);
  const [voices, setVoices] = useState<any[]>([]);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  const [step, setStep] = useState(0);
  const [onboarding, setOnboarding] = useState(!localStorage.getItem('acb-onboarded'));
  const [filter, setFilter] = useState('all');
  const [recipientDisplay, setRecipientDisplay] = useState('');
  const [audioUrl, setAudioUrl] = useState('');
  const [recordAudioUrl, setRecordAudioUrl] = useState('');
  async function refresh() {
    const [s, e, n, d] = await Promise.all([api('/status'), api('/events'), api('/notifications'), api('/decisions')]);
    setStatus(s); setEvents(Array.isArray(e) ? e : e.events ?? []); setNotifications(Array.isArray(n) ? n : n.notifications ?? []); setDecisions(Array.isArray(d) ? d : d.decisions ?? []);
  }
  useEffect(() => {
    let disposed = false;
    api('/config').then(c => { if (!disposed) { setConfig(c.config ?? c); setRecipientDisplay(c.recipientDisplay ?? c.recipient?.display ?? ''); } }).catch(e => !disposed && setError(e.message));
    api('/voices').then(v => !disposed && setVoices(Array.isArray(v) ? v : v.voices ?? [])).catch(() => !disposed && setNotice('本机语音暂不可用；仍可配置服务、接入 Agent 和查看通知。'));
    api('/integration').then(i => !disposed && setIntegration(i)).catch(e => !disposed && setError(e.message));
    const tick = () => { if (!disposed) refresh().catch(e => !disposed && setError(e.message)); };
    tick(); const id = setInterval(tick, 2500);
    return () => { disposed = true; clearInterval(id); };
  }, []);
  useEffect(() => () => { if (audioUrl) URL.revokeObjectURL(audioUrl); }, [audioUrl]);
  async function act(action: () => Promise<any>, message?: string) {
    setBusy(true); setError(''); setNotice('');
    try { const result = await action(); if (message) setNotice(message); await refresh(); return result; } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function save() { if (!config) return; const result = await api('/config', config, 'PUT'); setConfig(result.config ?? result); setRecipientDisplay(result.recipientDisplay ?? result.recipient?.display ?? recipientDisplay); return result; }
  async function preview() {
    const response = await fetch('/api/voice/preview', { method: 'POST', headers: { Authorization: `Bearer ${token()}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ text: '你好，你的任务有了新进展。这是 Agent Call Bridge 的本地中文试听。', voice: config?.voice.name, rate: config?.voice.rate }) });
    if (!response.ok) { const data = await response.json(); throw new Error(data.message ?? '语音生成失败'); }
    const url = URL.createObjectURL(await response.blob()); setAudioUrl(url);
  }
  async function previewNotification(id: string) {
    const response = await fetch('/api/notifications/' + encodeURIComponent(id) + '/preview', { method: 'POST', headers: { Authorization: 'Bearer ' + token() } });
    if (!response.ok) { const value = await response.json(); throw new Error(value.error ?? '汇报试听失败'); }
    if (recordAudioUrl) URL.revokeObjectURL(recordAudioUrl);
    setRecordAudioUrl(URL.createObjectURL(await response.blob()));
  }
  const pending = decisions.filter(d => d.status === 'pending');
  const mode: ProviderId = status?.mode ?? config?.mode ?? 'mock';
  const patch = (section: keyof AppConfig, key: string, value: unknown) => setConfig(c => c ? { ...c, [section]: { ...(c[section] as object), [key]: value } } : c);
  const providerPatch = (provider: ProviderId, key: string, value: unknown) => setConfig(c => c && provider !== 'mock' ? { ...c, providers: { ...c.providers, [provider]: { ...c.providers[provider], [key]: value } } } : c);
  const providerForm = config && <>
    <Field label="电话服务"><select value={config.mode} onChange={e => setConfig({ ...config, mode: e.target.value as ProviderId })}>{Object.entries(names).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field>
    <ProviderHelp provider={config.mode}/>
    {config.mode === 'mock' && <div className="soft-note"><Icon name="shield"/><p>无需账号，也不会拨打任何号码。完整体验事件处理、中文语音和回复流程。</p></div>}
    {config.mode === 'twilio' && <><div className="warning">Twilio 不支持中国大陆 +86 外呼。其他地区也需要可用线路、主叫和账号权限。</div>{(['accountSid', 'authToken', 'from', 'callbackBaseUrl'] as const).map(key => <Field key={key} label={{ accountSid: 'Account SID', authToken: 'Auth Token', from: '主叫号码', callbackBaseUrl: 'HTTPS 回调地址' }[key]} help={key === 'authToken' ? '仅保存在本机；留空保留已保存值。' : undefined}><input autoComplete="off" type={key === 'authToken' ? 'password' : 'text'} value={config.providers.twilio[key] ?? ''} onChange={e => providerPatch('twilio', key, e.target.value)}/></Field>)}</>}
    {config.mode === 'aliyun' && <><div className="warning">仅符合要求的企业可申请，个人账号不可用。模板和语音资质须审核；填入 Key 不代表线路可用。</div>{(['accessKeyId', 'accessKeySecret', 'ttsCode', 'regionId'] as const).map(key => <Field key={key} label={{ accessKeyId: 'AccessKey ID', accessKeySecret: 'AccessKey Secret', ttsCode: '审核通过的公共模式模板', regionId: '区域' }[key]} help={key === 'ttsCode' ? '模板使用 task、status 两个变量，必须符合已审核范围。' : undefined}><input autoComplete="off" type={key.toLowerCase().includes('secret') ? 'password' : 'text'} value={config.providers.aliyun[key] ?? ''} onChange={e => providerPatch('aliyun', key, e.target.value)}/></Field>)}</>}
    {config.mode === 'sip' && <><div className="warning">实验性 SIP。局域网软件通话不等于 +86 手机外呼；当前版本不提供 TLS/SRTP。</div>{(['server', 'username', 'password', 'extension', 'port', 'executable'] as const).map(key => <Field key={key} label={{ server: 'SIP 服务器', username: '账号', password: '密码', extension: '目标分机 / SIP 地址', port: '端口', executable: 'baresip 程序路径' }[key]}><input type={key === 'password' ? 'password' : key === 'port' ? 'number' : 'text'} autoComplete="off" value={config.providers.sip[key] ?? ''} onChange={e => providerPatch('sip', key, key === 'port' ? Number(e.target.value) : e.target.value)}/></Field>)}</>}
  </>;
  const recipientForm = config && (config.mode === 'sip' ? <><p className="muted">SIP 通知使用右侧配置的服务器和目标分机，不需要填写手机号。</p><label className="check"><input type="checkbox" checked={config.recipient.consent} onChange={e => patch('recipient', 'consent', e.target.checked)}/>该分机由我接听，或已获得接听人明确同意</label></> : <>
    <div className="form-row"><Field label="区号"><select value={config.recipient.countryCode} onChange={e => patch('recipient', 'countryCode', e.target.value)}><option value="+86">中国大陆 +86</option><option value="+1">美国 / 加拿大 +1</option><option value="+852">中国香港 +852</option><option value="+886">中国台湾 +886</option><option value="+44">英国 +44</option><option value="+81">日本 +81</option><option value="+65">新加坡 +65</option></select></Field><Field label="手机号码" help={recipientDisplay ? `已保存：${recipientDisplay}；留空保留。` : '演示模式可留空。'}><input type="tel" autoComplete="off" value={config.recipient.number ?? ''} placeholder="输入本人或已同意接听的号码" onChange={e => patch('recipient', 'number', e.target.value)}/></Field></div>
    <label className="check"><input type="checkbox" checked={config.recipient.consent} onChange={e => patch('recipient', 'consent', e.target.checked)}/>这是我的号码，或已获得接听人的明确同意</label>
    <p className="muted">个人 +86 手机外呼线路尚未落实。你仍可完成演示和 Agent 接入。</p>
  </>);
  const voiceForm = config && <><div className="form-row"><Field label="中文音色"><select value={config.voice.name} onChange={e => patch('voice', 'name', e.target.value)}><option value="">系统默认中文语音</option>{voices.map(v => <option key={v.id ?? v.name} value={v.id ?? v.name}>{v.name}</option>)}</select></Field><Field label={`语速 · ${config.voice.rate}`}><input type="range" min="-5" max="5" value={config.voice.rate} onChange={e => patch('voice', 'rate', Number(e.target.value))}/></Field></div><button className="button secondary" disabled={busy} onClick={() => act(preview, '试听已生成，可点击播放器收听。')}><Icon name="wave"/>生成中文试听</button>{audioUrl && <audio controls src={audioUrl} aria-label="中文语音试听"/>}</>;
  function renderRecords(limit?: number) {
    const rows = notifications.filter(n => filter === 'all' || n.provider === filter || n.mode === filter).slice(0, limit);
    return rows.length ? <div className="table-wrap"><table><thead><tr><th>任务 / 汇报</th><th>通道</th><th>状态</th><th>时间</th></tr></thead><tbody>{rows.map(n => <tr key={n.id ?? n.notificationId}><td><strong>{n.summary ?? n.text ?? n.request?.text ?? n.taskId ?? '任务通知'}</strong><small>{n.message ?? n.lastError ?? n.reason ?? n.taskId}</small><button className="text-button" disabled={busy} onClick={() => act(() => previewNotification(n.id ?? n.notificationId), '本条汇报已生成本地试听，没有拨打电话')}>试听这条汇报</button></td><td><span className="tag">{names[(n.provider ?? n.mode ?? 'mock') as ProviderId] ?? n.provider}</span></td><td><span className={`state state-${n.status}`}>{(n.provider ?? n.mode) !== 'mock' && n.status === 'completed' ? '服务商报告完成' : statusNames[n.status] ?? n.status}</span></td><td className="nowrap">{dt(n.createdAt ?? n.created_at)}</td></tr>)}</tbody></table></div> : <div className="empty"><Icon name="phone" size={32}/><h3>等待第一条任务消息</h3><p>接入 Agent 或运行一次模拟测试，通知就会显示在这里。</p></div>;
  }
  const tabs = [{ id: 'overview', label: '工作台', icon: 'grid' }, { id: 'integration', label: 'Agent 接入', icon: 'link' }, { id: 'settings', label: '通话设置', icon: 'settings' }, { id: 'history', label: '通知记录', icon: 'list' }];
  return <div className="shell"><aside className="sidebar"><a href="#" className="brand" onClick={e => { e.preventDefault(); setPage('overview'); }}><span className="brand-mark"><Icon size={23}/></span><span>Call Bridge<small>让任务进展，找到你</small></span></a><div className="nav-label">工作空间</div><nav aria-label="主导航">{tabs.map(t => <button key={t.id} aria-label={t.label} aria-current={page === t.id ? 'page' : undefined} className={page === t.id ? 'active' : ''} onClick={() => setPage(t.id)}><Icon name={t.icon}/>{t.label}{t.id === 'overview' && pending.length > 0 && <b>{pending.length}</b>}</button>)}</nav><div className="sidebar-footer"><div className="local-indicator"><i/>仅本机访问</div><p>你的配置留在本机。<br/>真实拨号始终需要授权。</p><span>AGENT CALL BRIDGE · v0.1.3</span></div></aside>
    <main><header className="topbar"><span>个人工作空间 <span className="separator">/</span> {tabs.find(t => t.id === page)?.label}</span><div><span className={`pill ${status?.paused ? 'paused' : ''}`}><i/>{status?.paused ? '通知已暂停' : status ? 'Bridge 运行中' : '连接中'}</span><button className="stop-button" disabled={!status || busy} onClick={() => act(() => api('/pause', { paused: !status.paused }), status?.paused ? '通知已恢复' : '已暂停新通知，并尝试停止当前通话')}><Icon name={status?.paused ? 'play' : 'stop'} size={15}/>{status?.paused ? '恢复通知' : '紧急停止'}</button></div></header>
    <div className="content">{error && <div className="alert" role="alert"><strong>操作未完成</strong><span>{error}</span>{!token() && <p>请使用项目的“启动”入口重新打开工作台，获取本机会话。</p>}<button onClick={() => setError('')} aria-label="关闭错误">×</button></div>}{notice && <div className="notice" role="status"><Icon name="check"/>{notice}<button onClick={() => setNotice('')} aria-label="关闭提示">×</button></div>}
    {recordAudioUrl && <section className="panel"><h2>本条汇报 · 本地模拟试听</h2><audio controls src={recordAudioUrl} aria-label="通知语音试听"/></section>}
    {onboarding && config && <section className="onboarding"><div><span className="eyebrow">WELCOME / 首次使用</span><h2>先建立一条安心的连接</h2><p>可以从无费用的演示开始，之后再配置真实线路。</p></div><div className="steps">{['选择通道', '接听设置', '中文语音', '准备就绪'].map((text, i) => <button key={text} aria-current={step === i ? 'step' : undefined} className={step === i ? 'current' : ''} onClick={() => setStep(i)}><span>{i + 1}</span>{text}</button>)}</div><div className="onboarding-body">{step === 0 ? providerForm : step === 1 ? recipientForm : step === 2 ? voiceForm : <div className="soft-note"><Icon name="check"/><p>保存后可接入当前 Codex 项目。模拟测试不会拨打真实号码；真实电话仍处于锁定状态。</p></div>}</div><div className="actions"><button className="button secondary" onClick={() => { setOnboarding(false); localStorage.setItem('acb-onboarded', '1'); }}>稍后配置，进入工作台</button><button className="button" disabled={busy} onClick={() => step < 3 ? setStep(step + 1) : act(async () => { await save(); localStorage.setItem('acb-onboarded', '1'); setOnboarding(false); }, '设置已保存，真实拨号仍需单独授权')}>{step < 3 ? '下一步' : '保存并开始'}<Icon name="arrow" size={16}/></button></div></section>}
    {page === 'overview' && <><div className="page-heading"><div><span className="eyebrow">YOUR AGENT, WITHIN REACH</span><h1>每个重要进展，都不必错过。</h1><p>专注手头的事，把任务通知交给 Call Bridge。</p></div><button className="button secondary" onClick={() => { setOnboarding(true); setStep(0); }}>配置向导</button></div><section className="hero"><div className="hero-copy"><span className="hero-label"><i/>{names[mode]} · {status?.realCallsEnabled ? '真实通知已授权' : '真实拨号未启用'}</span><h2>{status?.paused ? '休息一下，通知已暂停。' : '让任务进展，找到你。'}</h2><p>{mode === 'mock' ? '先运行一次模拟通话，确认事件接入与中文语音已准备就绪。无需账号，也不会拨打真实电话。' : '连接设置与线路开通是不同步骤。我们会明确展示每一条通知的真实状态。'}</p><button className="button light" disabled={busy || !status} onClick={() => act(() => api('/test', {}), '模拟通知已发送，不会拨打真实号码')}><Icon name="play" size={16}/>运行模拟通话<Icon name="arrow" size={16}/></button></div><div className="signal-art" aria-hidden="true"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="phone-disc"><Icon size={45}/></div><span className="signal-label label-top"><i/>任务事件 · 自动汇报</span><span className="signal-label label-bottom"><Icon name="wave" size={16}/>中文语音 · 清晰传达</span></div></section>
    <div className="stats"><article><span><Icon name="link"/>已收到事件</span><strong>{events.length}<small> 条</small></strong><p>来自接入任务的状态信号</p></article><article><span><Icon name="phone"/>通知记录</span><strong>{notifications.length}<small> 条</small></strong><p>模拟与真实通道分别标记</p></article><article><span><Icon name="grid"/>等待你决定</span><strong className={pending.length ? 'orange' : ''}>{pending.length}<small> 项</small></strong><p>仅返回当前任务允许的选项</p></article><article><span><Icon name="wave"/>最近收到消息</span><strong className="time-value">{dt(status?.lastEventAt)}</strong><p>{status?.connectedAgents?.length ? `已发现 ${status.connectedAgents.length} 个 Agent 来源` : '等待 Agent 首次连接'}</p></article></div>
    {pending.length > 0 && <section className="panel decisions"><div className="section-head"><h2>Agent 正在等你</h2><span className="tag warm">{pending.length} 项待处理</span></div>{pending.map(d => <div className="decision" key={d.id}><div><span className="eyebrow">{d.taskId}</span><h3>{d.question}</h3><p>仅对当前等待中的任务生效 · 到期 {dt(d.expiresAt)}</p></div><div className="decision-options">{(d.options ?? []).map((o: any) => <button className="button secondary" key={o.id} disabled={busy} onClick={() => act(() => api(`/decisions/${d.id}/respond`, { optionId: o.id }), '答复已保存；等待中的原任务会收到结果')}>{o.label}</button>)}</div></div>)}</section>}
    <div className="overview-bottom"><section className="panel"><div className="section-head"><h2>最近通知</h2><button className="text-button" onClick={() => setPage('history')}>查看全部 <Icon name="arrow" size={14}/></button></div>{renderRecords(5)}</section><section className="panel connection-card"><span className="eyebrow">CONNECTION</span><h2>从任务到电话</h2><div className="flow"><div><b>01</b><span>Agent 上报<small>任务完成、失败或需要决定</small></span></div><div><b>02</b><span>Bridge 处理<small>去重、限频与允许操作检查</small></span></div><div><b>03</b><span>电话汇报<small>当前：{names[mode]}</small></span></div></div><button className="button secondary full" onClick={() => setPage('integration')}>接入我的 Agent<Icon name="arrow" size={16}/></button></section></div><div className="footnote"><Icon name="shield" size={16}/>个人 +86 外呼线路尚未落实。模拟和本地 SIP 通话不代表手机外呼成功。</div></>}

    {page === 'settings' && config && <><div className="page-heading"><div><span className="eyebrow">CALL PREFERENCES</span><h1>通话设置</h1><p>设置留在本机。保存配置不会授权或触发真实电话。</p></div><button className="button" disabled={busy} onClick={() => act(save, '设置已保存')}><Icon name="check" size={17}/>保存设置</button></div><div className="settings-grid"><section className="panel"><h2>接听人</h2>{recipientForm}<hr/><h2>中文语音</h2>{voiceForm}</section><section className="panel"><h2>服务与线路</h2>{providerForm}<button className="button secondary" disabled={busy} onClick={() => act(async () => { await save(); const r = await api('/providers/check', { provider: config.mode, remote: false }); setNotice(r.message ?? '本地配置检测完成'); }, undefined)}>检查配置与本地连接</button><p className="muted">默认检测不调用收费 API，也不等于运营商已开通。</p>{config.mode === 'sip' && <button className="button secondary" disabled={busy} onClick={() => act(async () => { await save(); const r = await api('/sip/register-check', { confirmation: '仅检测SIP注册，不拨号' }); setNotice(r.message ?? 'SIP 注册检测结束'); })}>检测 SIP 注册（不拨号）</button>}{config.mode === 'twilio' && <p className="muted">HTTPS 回调仅转发本机独立回调端口 17862，不能转发管理端口。需要服务商实际可访问的地址。</p>}</section><section className="panel"><h2>何时通知</h2>{Object.entries(eventNames).filter(([id]) => id !== 'turn_finished').map(([id, label]) => <label className="check" key={id}><input type="checkbox" checked={config.notification.types.includes(id as EventType)} onChange={e => patch('notification', 'types', e.target.checked ? [...config.notification.types, id] : config.notification.types.filter(t => t !== id))}/>{label}</label>)}<p className="muted">轮次结束不自动当作整个任务完成。没有活动只表示疑似无进展。</p></section><section className="panel"><h2>节制与保护</h2><div className="form-row"><Field label="同号码间隔（秒）"><input type="number" min="60" value={config.notification.cooldownSeconds} onChange={e => patch('notification', 'cooldownSeconds', Number(e.target.value))}/></Field><Field label="每小时最多（通）"><input type="number" min="1" max="3" value={config.notification.maxPerHour} onChange={e => patch('notification', 'maxPerHour', Number(e.target.value))}/></Field></div><div className="form-row"><Field label="每天最多（通）"><input type="number" min="1" max="10" value={config.notification.maxPerDay} onChange={e => patch('notification', 'maxPerDay', Number(e.target.value))}/></Field><Field label="无进展提醒（分钟）"><input type="number" min="5" value={config.notification.stallMinutes} onChange={e => patch('notification', 'stallMinutes', Number(e.target.value))}/></Field></div><Field label="电话控制 PIN" help="真实电话按键控制使用；留空保留。权限审批仍需回电脑处理。"><input type="password" autoComplete="new-password" inputMode="numeric" value={config.controlPin ?? ''} onChange={e => setConfig({ ...config, controlPin: e.target.value })}/></Field><div className="soft-note"><Icon name="shield"/><p>受理结果未知时不会自动重拨。更改目标或线路会使原真实拨号授权失效。</p></div></section></div></>}
    {page === 'integration' && <><div className="page-heading"><div><span className="eyebrow">AGENT CONNECTION</span><h1>沿用你的 Codex 工作流</h1><p>让 Agent 在当前项目中上报，不必改用另一个任务平台。</p></div></div><section className="panel integration-panel"><div className="section-head"><h2>接入当前项目</h2><span className="tag">{status?.connectedAgents?.length ? '已有 Agent 联系'  : integration?.installed ? '已安装，等待 Agent 联系' : '尚未安装'}</span></div><p>接入器会在本项目说明中加入可撤销的任务汇报约定，保留已有内容。当前 Agent 可直接使用 Bridge；无需复制密钥。</p><div className="actions"><button className="button" disabled={busy} onClick={() => act(async () => { const r = await api('/integration/install', {}); setIntegration(await api('/integration')); return r; }, '当前项目接入已安装；收到真实 Agent 上报后才算连接验证完成')}>接入当前项目<Icon name="arrow" size={16}/></button><button className="button secondary" onClick={() => act(async () => { setIntegration(await api('/integration')); }, '接入状态已刷新')}>刷新状态</button></div><div className="command"><span>供 Agent 使用的入口</span><code>{integration?.command ?? integration?.commands?.report ?? 'npm run bridge -- report --type task_completed --task-id <任务标识> --summary <简短汇报>'}</code></div><button className="button secondary" disabled={busy} onClick={() => act(async () => { const result = await api('/integration/codex-check', {}); if (!result.connected) throw new Error('协议握手未完成'); }, 'Codex 独立进程握手成功，未调用模型；不代表完整托管任务已验证')}>检测 Codex 协议（不调用模型）</button><div className="integration-columns"><article><h3>现有桌面任务</h3><p>Agent 通过现有终端工具上报。等待回复时，允许选项可以返回同一任务。</p><span className="tag">当前工作流优先</span></article><article><h3>已经结束的任务</h3><p>不能自动唤醒。回复保留在本地，需要回到原任务继续。</p><span className="tag neutral">明确边界</span></article><article><h3>产品托管任务</h3><p>使用独立 Codex 环境监控状态。登录与真实模型运行另行处理，不复制现有认证。</p><span className="tag neutral">单独验证</span></article></div></section><section className="panel"><h2>双向回复怎么工作</h2><p>Agent 上报一个问题及允许选项 → 工作台或电话回复 → Bridge 校验任务、有效期与一次性使用状态 → 等待中的原 Agent 收到结构化答复。</p><div className="soft-note"><Icon name="shield"/><p>电话中的话不会作为系统命令执行。命令、文件和网络权限审批仍须回到电脑处理。</p></div></section></>}
    {page === 'history' && <><div className="page-heading"><div><span className="eyebrow">NOTIFICATION HISTORY</span><h1>每一次汇报，都有记录</h1><p>受理、接通和任务完成是不同状态；模拟结果始终单独标记。</p></div><select aria-label="筛选通知通道" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">全部通道</option>{Object.entries(names).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div><section className="panel">{renderRecords()}</section><section className="panel"><div className="section-head"><h2>Agent 事件</h2><span className="tag">{events.length} 条</span></div>{events.length ? <div className="event-list">{events.slice(0, 30).map(e => <div key={e.eventId ?? e.id}><span className="event-dot"/><div><strong>{e.summary}</strong><small>{eventNames[e.type as EventType] ?? e.type} · {e.source} · {e.evidence?.kind === 'verified' ? '来源声明已验收' : 'Agent 上报'}</small></div><time>{dt(e.createdAt ?? e.occurredAt)}</time></div>)}</div> : <p className="muted">还没有收到事件。</p>}</section></>}
    {(page === 'settings' || page === 'history') && <RealCalls mode={mode} busy={busy} enabled={Boolean(status?.realCallsEnabled)} notifications={notifications} request={api} run={act}/>}
    </div><footer>Agent Call Bridge <span>本机优先 · 明确授权 · 真实记录</span></footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);

